### ISSUE TITLE
Write URL of PDF build back to repo as a commit status

### ISSUE THREAD

**Issue by arfon** [sharelatex/github-latex-ci#16]
Firstly, this service is awesome :zap: :sparkles: 

What would make it _even better_ would be if when there is a successful build of the TeX file, you posted back the URL to the PDF as a commit status: https://developer.github.com/v3/repos/statuses/

Alternatively (and possibly even better for user experience), if the build is happening in a Pull Request then you could post a comment back into the Pull Request with the URL for the paper.

Anyway, you get the idea - what do you think? :pray:

**Comment by jpallen** [comment]
I'd love to do this. The reason we don't is that we do everything so far with a client-based cookie for authentication. The flow is:

1) Log in
2) Use the session token to set up any webhooks
3) Listen for these webhooks on public repos.

This keeps the auth on our end super simple and means we don't need to store any sensitive info or manage log-ins ourselves. Unfortunately it also means we can't do anything on GitHub in response to the webhook since we don't have any auth credentials stored.

So yes, in principle I love the idea. In practice though it would be a huge amount of work as the project stands :(

**Comment by arfon** [comment]
> 2) Use the session token to set up any webhooks

Ahh, I'd missed that this was how you were authenticating. That makes sense why this is non-trivial.

For your future reference - I showed off this integration in a GitHub workshop this week to a bunch of astronomers, they loved it but wanted two things:

1. For the tool to work on private repositories
2. For the URL to be posted back into the Pull Request

**Comment by jpallen** [comment]
Cool, that makes a lot of sense. We would love to get this working with private repos, it's just we don't have the development time at the moment :(. I'm very open to other people running with this though if anyone is interested.
